### PR TITLE
module: add nixosModule metamodule

### PR DESCRIPTION
**Pull request by locallycompact**
@MatthewCroughan how can this be simpler?

### CODE REVIEW

**Review by MatthewCroughan — APPROVED** [review]
I do not think it can be simpler. I like it like this. Don't forget to change and test the tests I've made though, if necessary.

**Comment by srid** [comment]
Out of curiosity: why is this named `nixosModule` specifically?

**Comment by locallycompact** [comment]
It's on the output schema here. https://nixos.wiki/wiki/Flakes

Which says

```
  # Default module, consumed by other flakes
  nixosModule = { config }: { options = {}; config = {}; };
  ```
  
But it didn't feel very default-y so that's why I asked.

**Comment by MatthewCroughan** [comment]
@locallycompact If you're not happy with `nixosModule` you can always do `nixosModules.default` which is the same thing.

**Comment by MatthewCroughan** [comment]
Forgot to mention that yes, this looks good.

**Pull request merged**
